[package]
name = "aoc_2025_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"

[dev-dependencies]
criterion = "0.8.0"

[[bench]]
name = "bench_days"
harness = false

[profile.release]
opt-level = 3
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1